version: "3.9"

services:
  db:
    container_name: splunk-db
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - src/.env
    ports:
      - "5432:5432"

volumes:
  postgres_data: